export default [
  {
    type: "producthunt",
    name: "Producthunt",
    icon: "logos:producthunt",
    disabled: false,
    description: "Top products of the day",
    url: "https://www.producthunt.com/",
  },
  {
    type: "hackernews",
    name: "Hackernews",
    icon: "logos:ycombinator",
    disabled: false,
    description: "Hackernews home page",
    url: "https://news.ycombinator.com/",
  },
  {
    type: "github",
    name: "Github Trending",
    icon: "logos:github-icon",
    disabled: false,
    description: "Trending repositories on Github",
    url: "https://github.com/trending",
  },
  {
    type: "youtube",
    name: "Youtube",
    icon: "logos:youtube-icon",
    disabled: false,
    description: "Pick a channel and watch the latest videos",
    url: "https://www.youtube.com/",
  },
  {
    type: "dribbble",
    name: "Dribbble",
    icon: "logos:dribbble-icon",
    disabled: false,
    description: "Trending shots on Dribbble",
    url: "https://dribbble.com/",
  },
  {
    type: "google-news",
    name: "Google news",
    icon: "GoogleNews",
    disabled: false,
    description: "Top news from Google news for your country",
    url: "https://news.google.com/",
  },
  {
    type: "rss",
    name: "Publication or Blog",
    icon: "ph:rss-simple-bold",
    disabled: false,
    description: "Subscribe via RSS feed",
  },
  {
    type: "substack",
    name: "Substack publication",
    icon: "SubstackLogo",
    disabled: false,
    description: "Subscribe to a Substack publication",
  },
  {
    type: "github-notifications",
    name: "Github notifications",
    icon: "logos:github-icon",
    disabled: false,
    description: "Get all your Github notifications in one place",
  },
  {
    type: "github-issues",
    name: "Github issues",
    icon: "logos:github-icon",
    disabled: false,
    description: "Get all your Github issues",
  },
  {
    type: "google-calendar",
    name: "Calendar events",
    icon: "logos:google-calendar",
    disabled: false,
    description: "List of all events today from your Google calendar",
  },
  {
    type: "newsletter",
    name: "Newsletter",
    icon: "logos:google-gmail",
    disabled: false,
    description: "via Gmail (coming soon)",
  },
  {
    type: "iframe",
    name: "iFrame",
    icon: "heroicons:computer-desktop",
    disabled: false,
    description: "Add any website via iFrame",
  },
  {
    type: "linear",
    name: "Linear tickets",
    icon: "logos:linear-icon",
    disabled: false,
    description: "List of all your Linear tickets",
  },
  {
    type: "notepad",
    name: "Notepad",
    icon: "heroicons:document-text",
    disabled: false,
    description: "Simple notepad to your dashboard",
  },
  {
    type: "feedful-clips",
    name: "Feedful Clips",
    icon: "heroicons:bookmark",
    disabled: false,
    description: "Clips saved from the feedful browser extension",
  },
];
