export default [
  {
    id: 36928529,
    title: "Fighting for the Open Web [image]",
    points: 62,
    user: "pabs3",
    time: 1690699515,
    time_ago: "2 hours ago",
    comments_count: 30,
    type: "link",
    url: "https://www.davidrevoy.com/article982/fighting-for-the-open-web",
    domain: "davidrevoy.com",
  },
  {
    id: 36927695,
    title: "Welcome to Wikifunctions",
    points: 126,
    user: "edward",
    time: 1690689752,
    time_ago: "4 hours ago",
    comments_count: 39,
    type: "link",
    url: "https://www.wikifunctions.org/wiki/Wikifunctions:Main_Page",
    domain: "wikifunctions.org",
  },
  {
    id: 36905267,
    title:
      "Forced rhubarb, a vegetable deprived of sunlight, is having a renaissance (2019)",
    points: 73,
    user: "cellover",
    time: 1690542800,
    time_ago: "2 days ago",
    comments_count: 15,
    type: "link",
    url: "https://www.bbc.com/travel/article/20190424-the-english-vegetable-picked-by-candlelight",
    domain: "bbc.com",
  },
  {
    id: 36926569,
    title: "Snowflake",
    points: 147,
    user: "bcg361",
    time: 1690678792,
    time_ago: "7 hours ago",
    comments_count: 18,
    type: "link",
    url: "https://snowflake.torproject.org/",
    domain: "snowflake.torproject.org",
  },
  {
    id: 36917466,
    title: "Computer scientists discover limits of gradient descent",
    points: 51,
    user: "Anon84",
    time: 1690611728,
    time_ago: "a day ago",
    comments_count: 14,
    type: "link",
    url: "https://www.quantamagazine.org/computer-scientists-discover-limits-of-major-research-algorithm-20210817/",
    domain: "quantamagazine.org",
  },
  {
    id: 36926228,
    title: "ASML EUV lithography machine could keep Moore’s Law on track",
    points: 133,
    user: "mfiguiere",
    time: 1690675633,
    time_ago: "8 hours ago",
    comments_count: 87,
    type: "link",
    url: "https://spectrum.ieee.org/high-na-euv",
    domain: "spectrum.ieee.org",
  },
  {
    id: 36927971,
    title: "Comma 3X",
    points: 65,
    user: "Yenrabbit",
    time: 1690693189,
    time_ago: "3 hours ago",
    comments_count: 37,
    type: "link",
    url: "https://www.comma.ai/",
    domain: "comma.ai",
  },
  {
    id: 36924267,
    title: "Show HN: Gogit – Just enough Git (in Go) to push itself to GitHub",
    points: 129,
    user: "benhoyt",
    time: 1690662866,
    time_ago: "12 hours ago",
    comments_count: 57,
    type: "link",
    url: "https://benhoyt.com/writings/gogit/",
    domain: "benhoyt.com",
  },
  {
    id: 36928601,
    title: "PlayHT (YC W23) Is Hiring ML Engineers (LLMs, Generative AI)",
    points: null,
    user: null,
    time: 1690700446,
    time_ago: "an hour ago",
    comments_count: 0,
    type: "job",
    url: "https://www.ycombinator.com/companies/playht/jobs/G6vI660-senior-ml-engineer-large-language-models",
    domain: "ycombinator.com",
  },
  {
    id: 36921446,
    title: "Functions are vectors",
    points: 201,
    user: "TheNumbat",
    time: 1690646091,
    time_ago: "17 hours ago",
    comments_count: 70,
    type: "link",
    url: "https://thenumb.at/Functions-are-Vectors/",
    domain: "thenumb.at",
  },
  {
    id: 36927940,
    title: "Microbially produced protein that is much sweeter than sugar",
    points: 108,
    user: "walterbell",
    time: 1690692862,
    time_ago: "4 hours ago",
    comments_count: 65,
    type: "link",
    url: "https://www.nature.com/articles/s41587-023-01865-x",
    domain: "nature.com",
  },
  {
    id: 36916982,
    title: "Blue iceberg",
    points: 29,
    user: "thunderbong",
    time: 1690605386,
    time_ago: "a day ago",
    comments_count: 6,
    type: "link",
    url: "https://en.wikipedia.org/wiki/Blue_iceberg",
    domain: "en.wikipedia.org",
  },
  {
    id: 36926165,
    title: "Button Pushes You (2022)",
    points: 79,
    user: "john-doe",
    time: 1690675101,
    time_ago: "8 hours ago",
    comments_count: 20,
    type: "link",
    url: "https://despens.systems/2022/06/button-pushes-you/",
    domain: "despens.systems",
  },
  {
    id: 36928485,
    title: "Why I use the D programming language for scripting (2021)",
    points: 25,
    user: "teleforce",
    time: 1690698979,
    time_ago: "2 hours ago",
    comments_count: 4,
    type: "link",
    url: "https://opensource.com/article/21/1/d-scripting",
    domain: "opensource.com",
  },
  {
    id: 36922790,
    title: "Open Source Outdoor Air Quality Monitor",
    points: 175,
    user: "ahaucnx",
    time: 1690653544,
    time_ago: "14 hours ago",
    comments_count: 83,
    type: "link",
    url: "https://www.airgradient.com/open-air/",
    domain: "airgradient.com",
  },
  {
    id: 36917552,
    title: "Code Duello: The Rules of Dueling (1963)",
    points: 13,
    user: "thunderbong",
    time: 1690612794,
    time_ago: "a day ago",
    comments_count: 3,
    type: "link",
    url: "https://www.pbs.org/wgbh/americanexperience/features/duel-code-duello-rules-dueling/",
    domain: "pbs.org",
  },
  {
    id: 36922744,
    title: "How fast should you accelerate your kid in math?",
    points: 110,
    user: "sebg",
    time: 1690653238,
    time_ago: "15 hours ago",
    comments_count: 194,
    type: "link",
    url: "https://kidswholovemath.substack.com/p/how-fast-should-you-accelerate-your",
    domain: "kidswholovemath.substack.com",
  },
  {
    id: 36922517,
    title: "US Army Field Manual on Leadership (1990) [pdf]",
    points: 197,
    user: "jtlicardo",
    time: 1690651962,
    time_ago: "15 hours ago",
    comments_count: 105,
    type: "link",
    url: "https://armyoe.files.wordpress.com/2018/03/1990-fm-22-100.pdf",
    domain: "armyoe.files.wordpress.com",
  },
  {
    id: 36924832,
    title: "Red algae proteins grafted into tobacco double plant growth",
    points: 95,
    user: "geox",
    time: 1690666048,
    time_ago: "11 hours ago",
    comments_count: 57,
    type: "link",
    url: "https://news.cornell.edu/stories/2023/07/red-algae-proteins-grafted-tobacco-double-plant-growth",
    domain: "news.cornell.edu",
  },
  {
    id: 36925688,
    title: "The papers were not ready for publication",
    points: 162,
    user: "Accujack",
    time: 1690671532,
    time_ago: "9 hours ago",
    comments_count: 87,
    type: "link",
    url: "https://twitter.com/8teAPi/status/1684385895565365248",
    domain: "twitter.com",
  },
  {
    id: 36921785,
    title: "The Problem of Excess Genius (1997)",
    points: 15,
    user: "jseliger",
    time: 1690647930,
    time_ago: "16 hours ago",
    comments_count: 16,
    type: "link",
    url: "https://www.visakanv.com/archives/2021/02/14/the-problem-of-excess-genius-by-david-banks-1997/",
    domain: "visakanv.com",
  },
  {
    id: 36928043,
    title: "What I Would Do If I Ran Tarsnap",
    points: 10,
    user: "reubano",
    time: 1690694036,
    time_ago: "3 hours ago",
    comments_count: 2,
    type: "link",
    url: "https://www.kalzumeus.com/2014/04/03/fantasy-tarsnap/",
    domain: "kalzumeus.com",
  },
  {
    id: 36926852,
    title: "GNU Boot sent a cease and desist to Libreboot",
    points: 228,
    user: "codingcoyote",
    time: 1690681225,
    time_ago: "7 hours ago",
    comments_count: 145,
    type: "link",
    url: "https://libreboot.org/news/gnuboot.html#gnu-boot-cease-and-desist-email",
    domain: "libreboot.org",
  },
  {
    id: 36908369,
    title: "The bigger the interface, the weaker the abstraction",
    points: 59,
    user: "zdw",
    time: 1690558267,
    time_ago: "2 days ago",
    comments_count: 39,
    type: "link",
    url: "https://functionallyimperative.com/p/the-bigger-the-interface-the-weaker",
    domain: "functionallyimperative.com",
  },
  {
    id: 36927624,
    title: "Unsafe deserialization vulnerability in many Minecraft mods",
    points: 29,
    user: "davikr",
    time: 1690688773,
    time_ago: "5 hours ago",
    comments_count: 6,
    type: "link",
    url: "https://github.com/dogboy21/serializationisbad",
    domain: "github.com",
  },
  {
    id: 36923562,
    title: "The Transformer Blueprint",
    points: 59,
    user: "nyandwi",
    time: 1690658515,
    time_ago: "13 hours ago",
    comments_count: 7,
    type: "link",
    url: "https://deeprevision.github.io/posts/001-transformer/",
    domain: "deeprevision.github.io",
  },
  {
    id: 36917802,
    title: "Larne Craigyhill bonfire: 17000 pallets (2021)",
    points: 17,
    user: "daverol",
    time: 1690615770,
    time_ago: "a day ago",
    comments_count: 47,
    type: "link",
    url: "https://www.belfastlive.co.uk/news/larne-craigyhill-bonfire-more-17000-20989400",
    domain: "belfastlive.co.uk",
  },
  {
    id: 36917290,
    title: "Birdga.me",
    points: 9,
    user: "dearwell",
    time: 1690609393,
    time_ago: "a day ago",
    comments_count: 3,
    type: "link",
    url: "https://birdga.me/harsh-division",
    domain: "birdga.me",
  },
  {
    id: 36902351,
    title: "The Wrath of Goodreads",
    points: 49,
    user: "fortran77",
    time: 1690509397,
    time_ago: "2 days ago",
    comments_count: 65,
    type: "link",
    url: "https://www.theatlantic.com/ideas/archive/2023/07/goodreads-review-bombing-amazon-moderation/674811/",
    domain: "theatlantic.com",
  },
  {
    id: 36919981,
    title: "The Hacker's Dictionary",
    points: 112,
    user: "derealized",
    time: 1690636439,
    time_ago: "19 hours ago",
    comments_count: 38,
    type: "link",
    url: "http://www.hackersdictionary.com/html/index.html",
    domain: "hackersdictionary.com",
  },
];
